import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/QueryProvider";
import { AuthProvider } from "@/lib/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"]
});

export const metadata = {
  title: "Watchflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} antialiased`}
      >
          <QueryProvider>
              <AuthProvider>
                  {children}
              </AuthProvider>
          </QueryProvider>
      </body>
    </html>
  );
}
